# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-12 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160312_0446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtask',
            old_name='project',
            new_name='maintask',
        ),
    ]
