# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='duration',
            new_name='practical_hrs',
        ),
        migrations.RenameField(
            model_name='coursemodule',
            old_name='duration',
            new_name='practical_hrs',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='duration',
            new_name='practical_hrs',
        ),
        migrations.AddField(
            model_name='course',
            name='theory_hrs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='theory_hrs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='theory_hrs',
            field=models.IntegerField(default=0),
        ),
    ]
