# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 01:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('course', '0002_auto_20160207_0759'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
                ('student', models.ManyToManyField(related_name='student', to='auth.Group')),
                ('teacher', models.ManyToManyField(related_name='teacher', to='auth.Group')),
            ],
        ),
    ]
