# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 01:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_coursegroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachers_diary',
            old_name='course_completed',
            new_name='completed',
        ),
    ]
