# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 10:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20160208_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegroup',
            name='student',
            field=models.ManyToManyField(related_name='student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coursegroup',
            name='teacher',
            field=models.ManyToManyField(related_name='teacher', to=settings.AUTH_USER_MODEL),
        ),
    ]
