# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 21:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_auto_20160208_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegroup',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
