# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_auto_20160208_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers_diary',
            name='coursegroup',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.CourseGroup'),
            preserve_default=False,
        ),
    ]
