# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_activity_iscompleted'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lesson_Schedule',
            new_name='Theory_Lesson_Schedule',
        ),
    ]
