# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_auto_20160222_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Practical_Lesson_Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tobecompleted', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Activity')),
                ('coursegroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseGroup')),
            ],
        ),
    ]
